### ISSUE TITLE
Rare case of getting stuck if placing a block under my feet

### ISSUE THREAD

**Issue by rndtrash** [SpadesX/SpadesX#11]
https://user-images.githubusercontent.com/6745157/156943129-8d9b49e6-9990-4e77-9b66-fe8907bc4b2b.mp4

**Comment by rndtrash** [comment]
![Снимок экрана_2022-03-07_00-45-51](https://user-images.githubusercontent.com/6745157/156943470-c1dfdf16-0f28-4f4b-9a1d-c640320e2968.png)

**Comment by Haxk20** [comment]
Issue fixed by 566645b44cd365146ee87c049eb449af89e4e302 and later more proper solution found in 0b77522c23713e261a4e1f5e21fef2c550662ab9

Thanks for reporting the bug :)
