### ISSUE TITLE
Help wanted: Add capture limit to map config

### ISSUE THREAD

**Issue by Haxk20** [SpadesX/SpadesX#34]
This is a very good first contributor issue for someone.

Capture limit has to be per map and thus map needs to have a capture limit
in the config.
This will require a new variable in structs.
Loading and using it should be very easy otherwise.

**Comment by lokka30** [comment]
@Haxk20, is this config layout suitable for this?

```json
"capture-limits": {
        "default": 10,
        "Border_Hallway": 10
},
```

**Comment by Haxk20** [comment]
> @Haxk20, is this config layout suitable for this?
> 
> ```json
> "capture-limits": {
>         "default": 10,
>         "Border_Hallway": 10
> },
> ```

This should be in map config and default specified in the macros
