### ISSUE TITLE
Can't get/capture intel in water

### ISSUE THREAD

**Issue by DryByte** [SpadesX/SpadesX#39]
**Description:**
* Can't get or capture the intel when tent/intel is in the water (if you not crouch on it).

**How to Reproduce:**
* Start the server using a map with water, where the intel can spawn on there. Join in the server and try to get the intel without crouching.

**Client used:** Voxlap (tried to use openspades, but my os keeps dropping packets)
**Map used:** https://aos.party/view/9

**Comment by nonperforming** [comment]
Can confirm. Have to crouch to pick it up

**Comment by Haxk20** [comment]
Fixed in: 91116a3
