### ISSUE TITLE
Help wanted: 3D coordinates support for map configurations

### ISSUE THREAD

**Issue by lancilloty** [SpadesX/SpadesX#45]
**Is your feature request related to a problem? Please describe.**
3D coordinates are not supported and when maps have spawns that have empty spaces under them, such as underground tunnels, the players spawn in the tunnels instead of the intended spawn location.

**Describe the solution you'd like**
Adding 3D coordinates support for map configurations when specifying locations.

**Describe alternatives you've considered**
Restricting map designs is an option but no other AoS server has those & a lot of maps wouldn't be supported because of this.

**Additional context**
The 2Fort map is awaiting addition to the repo https://github.com/SpadesX/Maps because the software doesn't yet support 3D coordinates.

**Comment by Haxk20** [comment]
@rndtrash Any progress on this since you assigned it to yourself ?
