### ISSUE TITLE
Predictable intel and player respawn coordinates

### ISSUE THREAD

**Issue by B1Z0N** [SpadesX/SpadesX#54]
Hello. Thanks for a wonderful app! Really tiny and minor security issue here.

From what I see in your server you use C standard `rand` to generate random data, like coordinates for game objects: [intel](https://github.com/SpadesX/SpadesX/blob/0d0706185683a17944eb2dbfbe326226374e2253/Source/Server/IntelTent.c#L187) and [player respawn](https://github.com/SpadesX/SpadesX/blob/0d0706185683a17944eb2dbfbe326226374e2253/Source/Server/Player.c#L108) points.

As it is [known](https://security.stackexchange.com/a/118999), libc uses **linear congruential pseudo-random number generator** (PRNG) that can be easily cracked given some inputs. 

So for example when doing some of the cups on this game, one command can achieve an unfair advantage knowing where the intel will be spawned and where the players' spawnpoints will be generated - being able to plan their offensive beforehand.

As for the proposed solution: you may use some more cryptosecure PRNG algos, for example **Mersenne Twister** PRNG or [any other](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator#Special_designs). For example you can see tiny implementation [here](https://github.com/ESultanik/mtwister).

**Comment by Haxk20** [comment]
Wonderful point. I knew about the security implications but didnt give it much thought since well respawn but yea player could figure out where exactly a player may spawn next.

I will add the tiny MT PRNG later. Holidays and all that :)

Thanks for pointing it out.

Happy holidays and happy new year :)

**Comment by Haxk20** [comment]
This has now been fixed in 8835f072507c6c5a9d20412432c983336231bdc4
