### ISSUE TITLE
Bug color text

### ISSUE THREAD

**Issue by X-DE1** [SpadesX/SpadesX#56]
Whit this version of SpadesX (https://aos.party/jenkins/job/SpadesX/lastSuccessfulBuild/artifact/build/) when you put this symbols in your name when you enter in SpadesX your name now is Limbo.
I think my name should appear ignoring those symbols because if I change the color of my name they wouldn't know which team I'm from red or blue.
![simbol](https://user-images.githubusercontent.com/101435795/210130189-0ed20c37-272c-433f-86d2-1316adb295bd.jpg)
![Limbo](https://user-images.githubusercontent.com/101435795/210130330-4065aefe-f77f-4a4a-8fe8-c556b0040821.jpg)

And if you put in periodic_messages or welcome_messages this symbols dont apper in red like if you copy and paste in the chat that text.
![Messeges](https://user-images.githubusercontent.com/101435795/210130295-d55581d1-31fb-4a1f-98c9-99aff70dca98.jpg)
![color](https://user-images.githubusercontent.com/101435795/210130308-05387ead-4a10-441c-956d-49e659dc96be.jpg)

[simbols and config.zip](https://github.com/SpadesX/SpadesX/files/10327078/simbols.and.config.zip)

**Comment by Haxk20** [comment]
The version on jenkins is outdated. This is fixed in latest version.

**Comment by X-DE1** [comment]
same thing happens when you do this
![SharedScreenshot](https://user-images.githubusercontent.com/101435795/210156043-01089c35-78bd-4c35-85db-76986121a2ea.jpg)

**Comment by Haxk20** [comment]
Well yes

IDK why it would take a message containing / as an real message instead of a command but oh well

As for the message in file thats to be expected. This was never meant to support that. Maybe it will in the future.

**Comment by Haxk20** [comment]
As for putting these symbols in your name thats also unsupported. Dont know if i will actually ever support that since its bit uhmmm useless.
